name: Smoke tests (Netlify + Render)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  smoke:
    name: Smoke test endpoints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (needed for workflow context)
        uses: actions/checkout@v4

      - name: Run endpoint probes
        run: |
          set -euo pipefail
          # Inject secrets into the environment (values are written to GITHUB_ENV)
          echo "NETLIFY_URL=${{ secrets.NETLIFY_URL }}" >> $GITHUB_ENV
          echo "RENDER_URL=${{ secrets.RENDER_URL }}" >> $GITHUB_ENV

          echo "NETLIFY_URL=${NETLIFY_URL:-<not set>}"
          echo "RENDER_URL=${RENDER_URL:-<not set>}"

          if [ -z "${NETLIFY_URL:-}" ] && [ -z "${RENDER_URL:-}" ]; then
            echo "No NETLIFY_URL or RENDER_URL secrets configured. Failing the job.";
            exit 1;
          fi

          if [ -n "${NETLIFY_URL:-}" ]; then
            echo "Testing frontend at $NETLIFY_URL";
            curl --fail --silent --show-error --location "$NETLIFY_URL" -o /dev/null;
            echo "Netlify OK";
          else
            echo "Skipping Netlify test (NETLIFY_URL not set)";
          fi

          if [ -n "${RENDER_URL:-}" ]; then
            echo "Testing backend health at $RENDER_URL/health";
            curl --fail --silent --show-error --location "$RENDER_URL/health" -o /dev/null;
            echo "Render health OK";
          else
            echo "Skipping Render test (RENDER_URL not set)";
          fi
